config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from haru import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("haru/", include("haru.urls")),
    path("", views.index, name="index"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

haru/urls.py
from django.urls import path

from . import views

app_name = "haru"

urlpatterns = [
    path("", views.index, name="index"),
    path("diary/create/", views.diary_create, name="diary_create"),
    path("diary/modify/<int:diary_id>/", views.diary_modify, name="diary_modify"),
    path("diary/delete/<int:diary_id>/", views.diary_delete, name="diary_delete"),
    path("calendar/", views.calendar_page, name="calendar_page"),
    path("all_diaries/", views.all_diaries, name="all_diaries"),
    path("statistics/", views.graph_page, name="graph_page"),
]

haru/models.py
from django.db import models
from django.contrib.auth.models import User


class Diary(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_diary"
    )
    content = models.TextField()
    create_date = models.DateField()

    # 감정 필드
    neutral = models.FloatField()
    happiness = models.FloatField()
    sadness = models.FloatField()
    angry = models.FloatField()
    disgust = models.FloatField()
    fear = models.FloatField()
    surprise = models.FloatField()
    primary_emotion = models.CharField(max_length=15)
    secondary_emotion = models.CharField(max_length=15)


class Emoji(models.Model):
    emotion = models.CharField(max_length=15)
    photo = models.ImageField(upload_to="emoji/images", blank=True)

    def __str__(self):
        return f"{self.emotion}.png"

haru/forms.py
from django import forms
from haru.models import Diary


class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary  # 사용할 모델
        fields = ["content"]  # DiaryForm에서 사용할 Diary 모델의 속성
        # labels = {
        #     "content": "내용",
        # }

haru/views.py
import requests
import json

from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from haru.forms import DiaryForm
from .models import Diary


@login_required(login_url="account:login")
def index(request):
    try:
        diary = Diary.objects.get(
            author_id=request.user.id,
            create_date=timezone.localdate(),
        )
        return redirect("haru:diary_modify", diary_id=diary.id)
    except:
        return redirect("haru:diary_create")


@login_required(login_url="account:login")
def diary_create(request):
    if request.method == "POST":
        form = DiaryForm(request.POST)
        if form.is_valid():
            diary = form.save(commit=False)
            diary.author = request.user
            diary.create_date = timezone.localdate()

            # request 요청으로 감성분석 모델로부터 감정분석 값 반환
            url = "http://15.165.255.212:50512/Diary"
            obj = {"Text": diary.content}
            emotion = json.loads(requests.post(url, json=obj).text)
            diary.neutral = emotion["neutral"]
            diary.happiness = emotion["happiness"]
            diary.sadness = emotion["sadness"]
            diary.angry = emotion["angry"]
            diary.disgust = emotion["disgust"]
            diary.fear = emotion["fear"]
            diary.surprise = emotion["surprise"]

            # 주요감정 순위별 정렬
            # emotion.pop("sentence")
            emotion_rank = sorted(emotion, key=lambda x: emotion[x], reverse=True)
            diary.primary_emotion = (
                emotion_rank[0] if emotion_rank[0] != ("neutral") else emotion_rank[1]
            )
            diary.secondary_emotion = (
                emotion_rank[1] if emotion_rank[1] != ("neutral") else emotion_rank[2]
            )
            diary.save()
            return redirect("haru:diary_modify", diary_id=diary.id)

    else:
        form = DiaryForm()
    context = {"form": form, "date": timezone.localdate()}
    return render(request, "haru/diary_form.html", context)


@login_required(login_url="account:login")
def diary_modify(request, diary_id):
    diary = get_object_or_404(Diary, pk=diary_id)
    if request.method == "POST":
        form = DiaryForm(request.POST, instance=diary)
        if form.is_valid():
            diary = form.save(commit=False)

            # request 요청으로 감성분석 모델로부터 감정분석 값 반환
            url = "http://15.165.255.212:50512/Diary"
            obj = {"Text": diary.content}
            emotion = json.loads(requests.post(url, json=obj).text)
            diary.neutral = emotion["neutral"]
            diary.happiness = emotion["happiness"]
            diary.sadness = emotion["sadness"]
            diary.angry = emotion["angry"]
            diary.disgust = emotion["disgust"]
            diary.fear = emotion["fear"]
            diary.surprise = emotion["surprise"]

            # 주요감정 순위별 정렬
            # emotion.pop("sentence")
            emotion_rank = sorted(emotion, key=lambda x: emotion[x], reverse=True)
            diary.primary_emotion = (
                emotion_rank[0] if emotion_rank[0] != ("neutral") else emotion_rank[1]
            )
            diary.secondary_emotion = (
                emotion_rank[1] if emotion_rank[1] != ("neutral") else emotion_rank[2]
            )
            diary.save()
    else:
        form = DiaryForm(instance=diary)

    # emotion_emojis = {
    #     "happiness": "😊",
    #     "sadness": "😭",
    #     "angry": "😡",
    #     "disgust": "🤮",
    #     "fear": "😨",
    #     "surprise": "😳",
    # }

    emotion_pt = {
        "neutral": int(diary.neutral * 100),
        "happiness": int(diary.happiness * 100),
        "sadness": int(diary.sadness * 100),
        "angry": int(diary.angry * 100),
        "disgust": int(diary.disgust * 100),
        "fear": int(diary.fear * 100),
        "surprise": int(diary.surprise * 100),
    }
    context = {
        "form": form,
        "diary": diary,
        "date": diary.create_date,
        # "primary_emotion": emotion_emojis[diary.primary_emotion],
        "emotion_pt": emotion_pt,
    }
    return render(request, "haru/diary_form.html", context)


@login_required(login_url="account:login")
def diary_delete(request, diary_id):
    diary = get_object_or_404(Diary, pk=diary_id)
    diary.delete()
    return redirect("haru:calendar_page")


@login_required(login_url="account:login")
def calendar_page(request):
    all_diaries = Diary.objects.filter(author_id=request.user.id)
    context = {"diaries": all_diaries}
    return render(request, "haru/fullcalendar.html", context)


@login_required(login_url="account:login")
def all_diaries(request):
    all_diaries = Diary.objects.filter(author_id=request.user.id)
    out = []
    emotion_emojis = {
        "happiness": "😊",
        "sadness": "😭",
        "angry": "😡",
        "disgust": "🤮",
        "fear": "😨",
        "surprise": "😳",
    }
    for diary in all_diaries:
        out.append(
            {
                # "title": emotion_emojis[diary.primary_emotion],
                "id": diary.id,
                "date": diary.create_date,
                "imageurl": f"../../media/emoji/images/{diary.primary_emotion}.png",
            }
        )

    return JsonResponse(out, safe=False)


@csrf_exempt
@login_required(login_url="account:login")
def graph_page(request):
    if request.method == "POST":
        range = json.loads(request.body)
        diaries = Diary.objects.filter(
            author_id=request.user.id, create_date__range=[range["start"], range["end"]]
        )

        neutral = diaries.filter(neutral__gt=0.0).aggregate(Sum("neutral"))
        neutral = (
            neutral["neutral__sum"] / diaries.count()
            if neutral["neutral__sum"]
            else 0.0
        )
        neutral *= 100

        happiness = diaries.filter(happiness__gt=0.0).aggregate(Sum("happiness"))
        happiness = (
            happiness["happiness__sum"] / diaries.count()
            if happiness["happiness__sum"]
            else 0.0
        )
        happiness *= 100

        sadness = diaries.filter(sadness__gt=0.0).aggregate(Sum("sadness"))
        sadness = (
            sadness["sadness__sum"] / diaries.count()
            if sadness["sadness__sum"]
            else 0.0
        )
        sadness *= 100

        angry = diaries.filter(angry__gt=0.0).aggregate(Sum("angry"))
        angry = angry["angry__sum"] / diaries.count() if angry["angry__sum"] else 0.0
        angry *= 100

        disgust = diaries.filter(disgust__gt=0.0).aggregate(Sum("disgust"))
        disgust = (
            disgust["disgust__sum"] / diaries.count()
            if disgust["disgust__sum"]
            else 0.0
        )
        disgust *= 100

        fear = diaries.filter(fear__gt=0.0).aggregate(Sum("fear"))
        fear = fear["fear__sum"] / diaries.count() if fear["fear__sum"] else 0.0
        fear *= 100

        surprise = diaries.filter(surprise__gt=0.0).aggregate(Sum("surprise"))
        surprise = (
            surprise["surprise__sum"] / diaries.count()
            if surprise["surprise__sum"]
            else 0.0
        )
        surprise *= 100

        statistics = {
            "neutral": neutral,
            "happiness": happiness,
            "sadness": sadness,
            "angry": angry,
            "disgust": disgust,
            "fear": fear,
            "surprise": surprise,
        }

        context = {"statistics": json.dumps(statistics)}
        # print(context)
        # return render(request, "haru/statistics.html", context)
        return JsonResponse(context, status=200)

    else:
        try:
            diary = Diary.objects.get(
                author_id=request.user.id, create_date=timezone.localdate()
            )
            neutral = diary.neutral * 100
            happiness = diary.happiness * 100
            sadness = diary.sadness * 100
            angry = diary.angry * 100
            disgust = diary.disgust * 100
            fear = diary.fear * 100
            surprise = diary.surprise * 100
        except:
            neutral = 0
            happiness = 0
            sadness = 0
            angry = 0
            disgust = 0
            fear = 0
            surprise = 0

        statistics = {
            "neutral": neutral,
            "happiness": happiness,
            "sadness": sadness,
            "angry": angry,
            "disgust": disgust,
            "fear": fear,
            "surprise": surprise,
        }

        context = {"statistics": json.dumps(statistics)}
        return render(request, "haru/statistics.html", context)

templates/haru/diary_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <!-- 오류표시 Start -->
            {% include 'form_errors.html' %}
            <!-- 오류표시 End -->
            <div class="mb-3">
                <h4 class="mt-5">{{ date }}</h4>
                {#                {% if primary_emotion %}#}
                {#                    <h5 style="color: gray;">감정분석 결과 : <span style="font-size:200%">{{ primary_emotion }}</span>#}
                {#                    </h5>{% endif %}#}
                {% if emotion_pt %}
                    <h5 style="color: gray;">감정분석 결과:
                        <span style="color: rgba(195, 192, 187, 1)">중립({{ emotion_pt.neutral }}%), </span>
                        <span style="color: rgba(54, 162, 235, 1)">😊 행복({{ emotion_pt.happiness }}%)</span>,
                        <span style="color: rgba(255, 206, 86, 1)">😭 슬픔({{ emotion_pt.sadness }}%)</span>,
                        <span style="color: rgba(255, 99, 132, 1)">😡 분노({{ emotion_pt.angry }}%)</span>,
                        <span style="color: rgba(153, 102, 255, 1)">🤮 혐오({{ emotion_pt.disgust }}%), </span>
                        <span style="color: rgba(75, 192, 192, 1)">😨 공포({{ emotion_pt.fear }}%), </span>
                        <span style="color: rgba(255, 159, 64, 1)">😳 놀람({{ emotion_pt.surprise }}%)</span>
                    </h5>
                {% endif %}
                <textarea class="form-control" name="content" id="content" rows="20" style="resize: none"
                          placeholder="오늘 하루를 기록해주세요.">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <div class="d-grid">
                {% if form.content.value %}
                    <button type="submit" class="btn btn-primary" id="model">수정</button>
                    <a href="javascript:void(0)" class="delete btn btn-outline-secondary"
                       data-uri="{% url 'haru:diary_delete' diary.id %}">삭제</a>
                    {#                    <a href="{% url 'haru:diary_delete' diary.id %}" class="btn btn-secondary">삭제</a>#}
                {% else %}
                    <button type="submit" class="btn btn-primary" id="model">저장</button>
                {% endif %}


            </div>
        </form>
    </div>
    <div id="overlay" style="display:none;">
        <div class="spinner"></div>
        <br/>
        Loading...
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#model').click(function () {
                $('#overlay').fadeIn().delay(50000).fadeOut();
            });
        });
        const delete_elements = document.getElementsByClassName("delete");
        Array.from(delete_elements).forEach(function (element) {
            element.addEventListener('click', function () {
                if (confirm("정말로 삭제하시겠습니까?")) {
                    location.href = this.dataset.uri;
                }
            });
        });
    </script>
{% endblock %}

templates/haru/diary_write.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <!-- 오류표시 Start -->
            {% include 'form_errors.html' %}
            <!-- 오류표시 End -->
            <div class="mb-3">
                <h5 class="mt-5">{{ today }}</h5>
                <textarea class="form-control" name="content" id="content" rows="20"
                          placeholder="오늘 하루를 기록해주세요.">{{ diary.content }}</textarea>
            </div>
            <div class="d-grid">
                {% if diary %}
                    <button type="submit" class="btn btn-primary">수정</button>
                    <button type="submit" class="btn btn-secondary">삭제</button>
                {% else %}
                    <button type="submit" class="btn btn-primary">저장</button>
                {% endif %}


            </div>
        </form>
    </div>
{% endblock %}

templates/haru/fullcalendar.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="mt-2" id="calendar"></div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            const calendar = $('#calendar').fullCalendar({
                events: '/haru/all_diaries',
                {#selectable: true,#}
                {#selectHelper: true,#}
                {#editable: true,#}
                {#eventLimit: true,#}
                showNonCurrentDates: false,
                contentHeight: 700,
                backgroundColor: '#378006',
                eventClick: function (event) {
                    const id = event.id;
                    $(location).prop('href', `http://http://15.165.121.165//haru/diary/modify/${id}`);
                },
                eventRender: function (event, eventElement) {
                    if (event.imageurl) {
                        eventElement.find("span.fc-title").prepend("<center><img src='" + event.imageurl + "' width='35%' height='35%'><center>");
                        eventElement.css({
                            'background-color': 'white',
                            'border-color': 'white',
                        });
                    }
                },
            });
        })
    </script>
{% endblock %}

templates/haru/statistics.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="mt-3 mb-3">
            <span class="p-2">🗓️</span>
            <input type="text" name="daterange" id="txtDate" style="width: 210px; text-align: center;"/>
        </div>
        <canvas id="myChart"></canvas>
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript">
        $(function () {
            var ctx = document.getElementById('myChart');
            let statistics = JSON.parse("{{ statistics | escapejs }}");
            let myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: ['중립', '😀 행복', '😭 슬픔', '😡 분노', '🤮 혐오', '😨 공포', '😳 놀람'],
                    datasets: [{
                        label: '감정 통계',
                        data: [statistics["neutral"], statistics["happiness"], statistics["sadness"], statistics["angry"], statistics["disgust"], statistics["fear"], statistics["surprise"]],
                        backgroundColor: [
                            'rgba(195, 192, 187, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(195, 192, 187, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(255, 99, 132, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1,
                    }]
                },
                options: {
                    legend: {
                        display: false,
                    },
                    scales: {
                        xAxes: [{
                            barPercentage: 0.5,
                            ticks: {
                                fontSize: 20,
                            },
                        }],
                        yAxes: [{
                            ticks: {
                                min: 0,
                                max: 100,
                                fontSize: 14,
                                callback: function (value) {
                                    return value + "%"
                                }
                            },
                        }]
                    }
                }
            });
            $('#txtDate').daterangepicker({
                locale: {
                    "separator": " ~ ",                     // 시작일시와 종료일시 구분자
                    "format": 'YYYY-MM-DD',     // 일시 노출 포맷
                    "applyLabel": "확인",                    // 확인 버튼 텍스트
                    "cancelLabel": "취소",                   // 취소 버튼 텍스트
                    "daysOfWeek": ["일", "월", "화", "수", "목", "금", "토"],
                    "monthNames": ["1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월"]
                },
                showDropdowns: true,                     // 년월 수동 설정 여부
                {#autoApply: true,                         // 확인/취소 버튼 사용여부#}
                timePicker24Hour: true,                  // 24시간 노출 여부(ex> true : 23:50, false : PM 11:50)
                timePickerSeconds: true,                 // 초 노출 여부
                minDate: new Date('2023-01-01'),
                maxDate: new Date(),

            }, function (start, end, label) {
                data = {
                    "start": start.format('YYYY-MM-DD'),
                    "end": end.format('YYYY-MM-DD'),
                };
                $.ajax({
                    url: '{% url "haru:graph_page" %}',
                    type: 'POST',
                    dataType: "json",
                    data: JSON.stringify(data),
                    success: function (json) {
                        statistics = JSON.parse(json["statistics"])
                        let myChart = new Chart(ctx, {
                            type: 'bar',
                            data: {
                                labels: ['중립', '😀 행복', '😭 슬픔', '😡 분노', '🤮 혐오', '😨 공포', '😳 놀람'],
                                datasets: [{
                                    label: '감정 통계',
                                    data: [statistics["neutral"], statistics["happiness"], statistics["sadness"], statistics["angry"], statistics["disgust"], statistics["fear"], statistics["surprise"]],
                                    backgroundColor: [
                                        'rgba(195, 192, 187, 0.2)',
                                        'rgba(54, 162, 235, 0.2)',
                                        'rgba(255, 206, 86, 0.2)',
                                        'rgba(255, 99, 132, 0.2)',
                                        'rgba(153, 102, 255, 0.2)',
                                        'rgba(75, 192, 192, 0.2)',
                                        'rgba(255, 159, 64, 0.2)'
                                    ],
                                    borderColor: [
                                        'rgba(195, 192, 187, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(255, 159, 64, 1)'
                                    ],
                                    borderWidth: 1
                                }]
                            },
                            options: {
                                legend: {
                                    display: false,
                                },
                                scales: {
                                    xAxes: [{
                                        barPercentage: 0.5,
                                        ticks: {
                                            fontSize: 20,
                                        },
                                    }],
                                    yAxes: [{
                                        ticks: {
                                            min: 0,
                                            max: 100,
                                            fontSize: 14,
                                            callback: function (value) {
                                                return value + "%"
                                            }
                                        },
                                    }]
                                }
                            }
                        });
                    },
                    error: function (xhr, errmsg, err) {
                        {#console.log(xhr.status + ": " + xhr.responseText);#}
                        console.log(err);
                        console.log(data);
                    }
                });
            });
        })
    </script>
{% endblock %}