account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from haru import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("haru/", include("haru.urls")),
    path("", views.index, name="index"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

haru/urls.py
from django.urls import path

from . import views

app_name = "haru"

urlpatterns = [
    path("", views.index, name="index"),
    path("diary/create/", views.diary_create, name="diary_create"),
    path("diary/modify/<int:diary_id>/", views.diary_modify, name="diary_modify"),
    path("diary/delete/<int:diary_id>/", views.diary_delete, name="diary_delete"),
    path("calendar/", views.calendar_page, name="calendar_page"),
    path("all_diaries/", views.all_diaries, name="all_diaries"),
    path("statistics/", views.graph_page, name="graph_page"),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <!-- haru CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <!-- fullcalendar -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.js"></script>
    <!-- 차트 링크 -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <!-- Date range picker -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"/>
    <title>Haru Diary</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include 'navbar.html' %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
<!-- For calendar -->
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/moment.min.js"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
    <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
            {% endif %}
        {% endfor %}
        <!-- 넌필드 오류 -->
        {% for error in form.non_field_errors %}
            <div>
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'haru:index' %}">Haru diary</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'haru:index' %}">일기쓰기</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'haru:calendar_page' %}">캘린더</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'haru:graph_page' %}">통계확인</a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'account:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'account:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    {% if not user.is_authenticated %}
                        <a href="{% url 'account:signup' %}" class="nav-link">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>